version: '2.1'
orbs: 
  aws-cli: circleci/aws-cli@4.1.0
jobs:
  credential_setup:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: dev
          role-arn: ${AWS_OIDC_ROLE_ARN}
          aws-region: us-west-2
      - run: 
        name: check-login
        command: | 
          aws sts get-caller-identity
workflows:
  test-aws-login:
    jobs:
      - credential-setup: 
          context: dev
