version: '2.1'
orbs: 
  aws-cli: circleci/aws-cli@4.1.0
jobs:
  credential-setup:
    executor: aws-cli/default
    steps:
      - checkout
      - run: 
          name: print-env
          command: |
            printenv
            echo "AWS_OIDC_ROLE_ARN: $AWS_OIDC_ROLE_ARN"
      - aws-cli/setup:
          profile_name: dev
          role_arn: ${AWS_OIDC_ROLE_ARN}
          region: us-west-2
      - run: 
          name: check-login
          command: | 
            aws sts get-caller-identity
workflows:
  test-aws-login:
    jobs:
      - credential-setup: 
          context: Dev
